/*
 * This file is generated by jOOQ.
 */
package com.taskable.jooq.tables.records;


import com.taskable.jooq.tables.Announcement;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AnnouncementRecord extends UpdatableRecordImpl<AnnouncementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>testdb.announcement.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb.announcement.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>testdb.announcement.classroom_id</code>.
     */
    public void setClassroomId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb.announcement.classroom_id</code>.
     */
    public Integer getClassroomId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>testdb.announcement.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>testdb.announcement.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>testdb.announcement.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>testdb.announcement.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>testdb.announcement.message</code>.
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>testdb.announcement.message</code>.
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>testdb.announcement.sent_at</code>.
     */
    public void setSentAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>testdb.announcement.sent_at</code>.
     */
    public LocalDateTime getSentAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnnouncementRecord
     */
    public AnnouncementRecord() {
        super(Announcement.ANNOUNCEMENT);
    }

    /**
     * Create a detached, initialised AnnouncementRecord
     */
    public AnnouncementRecord(Integer id, Integer classroomId, Integer userId, String title, String message, LocalDateTime sentAt) {
        super(Announcement.ANNOUNCEMENT);

        setId(id);
        setClassroomId(classroomId);
        setUserId(userId);
        setTitle(title);
        setMessage(message);
        setSentAt(sentAt);
        resetChangedOnNotNull();
    }
}
