/*
 * This file is generated by jOOQ.
 */
package com.taskable.jooq.tables.records;


import com.taskable.jooq.tables.Attachment;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttachmentRecord extends UpdatableRecordImpl<AttachmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>testdb.attachment.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb.attachment.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>testdb.attachment.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb.attachment.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>testdb.attachment.template_id</code>.
     */
    public void setTemplateId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>testdb.attachment.template_id</code>.
     */
    public Integer getTemplateId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>testdb.attachment.subtask_id</code>.
     */
    public void setSubtaskId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>testdb.attachment.subtask_id</code>.
     */
    public Integer getSubtaskId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>testdb.attachment.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>testdb.attachment.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>testdb.attachment.url</code>.
     */
    public void setUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>testdb.attachment.url</code>.
     */
    public String getUrl() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttachmentRecord
     */
    public AttachmentRecord() {
        super(Attachment.ATTACHMENT);
    }

    /**
     * Create a detached, initialised AttachmentRecord
     */
    public AttachmentRecord(Integer id, Integer projectId, Integer templateId, Integer subtaskId, String type, String url) {
        super(Attachment.ATTACHMENT);

        setId(id);
        setProjectId(projectId);
        setTemplateId(templateId);
        setSubtaskId(subtaskId);
        setType(type);
        setUrl(url);
        resetChangedOnNotNull();
    }
}
