/*
 * This file is generated by jOOQ.
 */
package com.taskable.jooq.tables.records;


import com.taskable.jooq.tables.Template;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TemplateRecord extends UpdatableRecordImpl<TemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>taskable.template.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>taskable.template.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>taskable.template.classroom_id</code>.
     */
    public void setClassroomId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>taskable.template.classroom_id</code>.
     */
    public Integer getClassroomId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>taskable.template.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>taskable.template.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>taskable.template.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>taskable.template.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>taskable.template.archived</code>.
     */
    public void setArchived(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>taskable.template.archived</code>.
     */
    public Byte getArchived() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TemplateRecord
     */
    public TemplateRecord() {
        super(Template.TEMPLATE);
    }

    /**
     * Create a detached, initialised TemplateRecord
     */
    public TemplateRecord(Integer id, Integer classroomId, String name, String description, Byte archived) {
        super(Template.TEMPLATE);

        setId(id);
        setClassroomId(classroomId);
        setName(name);
        setDescription(description);
        setArchived(archived);
        resetChangedOnNotNull();
    }
}
