// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.taskable.protobufs;

public final class AuthProto {
  private AuthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginExchangeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginExchangeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string authorization_code = 1;</code>
     * @return The authorizationCode.
     */
    java.lang.String getAuthorizationCode();
    /**
     * <code>string authorization_code = 1;</code>
     * @return The bytes for authorizationCode.
     */
    com.google.protobuf.ByteString
        getAuthorizationCodeBytes();
  }
  /**
   * Protobuf type {@code LoginExchangeRequest}
   */
  public static final class LoginExchangeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginExchangeRequest)
      LoginExchangeRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginExchangeRequest.newBuilder() to construct.
    private LoginExchangeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginExchangeRequest() {
      authorizationCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginExchangeRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taskable.protobufs.AuthProto.internal_static_LoginExchangeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taskable.protobufs.AuthProto.internal_static_LoginExchangeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taskable.protobufs.AuthProto.LoginExchangeRequest.class, com.taskable.protobufs.AuthProto.LoginExchangeRequest.Builder.class);
    }

    public static final int AUTHORIZATION_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object authorizationCode_;
    /**
     * <code>string authorization_code = 1;</code>
     * @return The authorizationCode.
     */
    @java.lang.Override
    public java.lang.String getAuthorizationCode() {
      java.lang.Object ref = authorizationCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorizationCode_ = s;
        return s;
      }
    }
    /**
     * <code>string authorization_code = 1;</code>
     * @return The bytes for authorizationCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorizationCodeBytes() {
      java.lang.Object ref = authorizationCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorizationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authorizationCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authorizationCode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authorizationCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authorizationCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taskable.protobufs.AuthProto.LoginExchangeRequest)) {
        return super.equals(obj);
      }
      com.taskable.protobufs.AuthProto.LoginExchangeRequest other = (com.taskable.protobufs.AuthProto.LoginExchangeRequest) obj;

      if (!getAuthorizationCode()
          .equals(other.getAuthorizationCode())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTHORIZATION_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorizationCode().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taskable.protobufs.AuthProto.LoginExchangeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginExchangeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginExchangeRequest)
        com.taskable.protobufs.AuthProto.LoginExchangeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taskable.protobufs.AuthProto.internal_static_LoginExchangeRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taskable.protobufs.AuthProto.internal_static_LoginExchangeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taskable.protobufs.AuthProto.LoginExchangeRequest.class, com.taskable.protobufs.AuthProto.LoginExchangeRequest.Builder.class);
      }

      // Construct using com.taskable.protobufs.AuthProto.LoginExchangeRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        authorizationCode_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taskable.protobufs.AuthProto.internal_static_LoginExchangeRequest_descriptor;
      }

      @java.lang.Override
      public com.taskable.protobufs.AuthProto.LoginExchangeRequest getDefaultInstanceForType() {
        return com.taskable.protobufs.AuthProto.LoginExchangeRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.taskable.protobufs.AuthProto.LoginExchangeRequest build() {
        com.taskable.protobufs.AuthProto.LoginExchangeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taskable.protobufs.AuthProto.LoginExchangeRequest buildPartial() {
        com.taskable.protobufs.AuthProto.LoginExchangeRequest result = new com.taskable.protobufs.AuthProto.LoginExchangeRequest(this);
        result.authorizationCode_ = authorizationCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taskable.protobufs.AuthProto.LoginExchangeRequest) {
          return mergeFrom((com.taskable.protobufs.AuthProto.LoginExchangeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taskable.protobufs.AuthProto.LoginExchangeRequest other) {
        if (other == com.taskable.protobufs.AuthProto.LoginExchangeRequest.getDefaultInstance()) return this;
        if (!other.getAuthorizationCode().isEmpty()) {
          authorizationCode_ = other.authorizationCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                authorizationCode_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object authorizationCode_ = "";
      /**
       * <code>string authorization_code = 1;</code>
       * @return The authorizationCode.
       */
      public java.lang.String getAuthorizationCode() {
        java.lang.Object ref = authorizationCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authorizationCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string authorization_code = 1;</code>
       * @return The bytes for authorizationCode.
       */
      public com.google.protobuf.ByteString
          getAuthorizationCodeBytes() {
        java.lang.Object ref = authorizationCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authorizationCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authorization_code = 1;</code>
       * @param value The authorizationCode to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authorizationCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authorization_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorizationCode() {
        
        authorizationCode_ = getDefaultInstance().getAuthorizationCode();
        onChanged();
        return this;
      }
      /**
       * <code>string authorization_code = 1;</code>
       * @param value The bytes for authorizationCode to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authorizationCode_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginExchangeRequest)
    }

    // @@protoc_insertion_point(class_scope:LoginExchangeRequest)
    private static final com.taskable.protobufs.AuthProto.LoginExchangeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taskable.protobufs.AuthProto.LoginExchangeRequest();
    }

    public static com.taskable.protobufs.AuthProto.LoginExchangeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginExchangeRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginExchangeRequest>() {
      @java.lang.Override
      public LoginExchangeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginExchangeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginExchangeRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taskable.protobufs.AuthProto.LoginExchangeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginExchangeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginExchangeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string csrf_token = 1;</code>
     * @return The csrfToken.
     */
    java.lang.String getCsrfToken();
    /**
     * <code>string csrf_token = 1;</code>
     * @return The bytes for csrfToken.
     */
    com.google.protobuf.ByteString
        getCsrfTokenBytes();
  }
  /**
   * Protobuf type {@code LoginExchangeResponse}
   */
  public static final class LoginExchangeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginExchangeResponse)
      LoginExchangeResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginExchangeResponse.newBuilder() to construct.
    private LoginExchangeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginExchangeResponse() {
      csrfToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginExchangeResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taskable.protobufs.AuthProto.internal_static_LoginExchangeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taskable.protobufs.AuthProto.internal_static_LoginExchangeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taskable.protobufs.AuthProto.LoginExchangeResponse.class, com.taskable.protobufs.AuthProto.LoginExchangeResponse.Builder.class);
    }

    public static final int CSRF_TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object csrfToken_;
    /**
     * <code>string csrf_token = 1;</code>
     * @return The csrfToken.
     */
    @java.lang.Override
    public java.lang.String getCsrfToken() {
      java.lang.Object ref = csrfToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        csrfToken_ = s;
        return s;
      }
    }
    /**
     * <code>string csrf_token = 1;</code>
     * @return The bytes for csrfToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCsrfTokenBytes() {
      java.lang.Object ref = csrfToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        csrfToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(csrfToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, csrfToken_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(csrfToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, csrfToken_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taskable.protobufs.AuthProto.LoginExchangeResponse)) {
        return super.equals(obj);
      }
      com.taskable.protobufs.AuthProto.LoginExchangeResponse other = (com.taskable.protobufs.AuthProto.LoginExchangeResponse) obj;

      if (!getCsrfToken()
          .equals(other.getCsrfToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CSRF_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getCsrfToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taskable.protobufs.AuthProto.LoginExchangeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginExchangeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginExchangeResponse)
        com.taskable.protobufs.AuthProto.LoginExchangeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taskable.protobufs.AuthProto.internal_static_LoginExchangeResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taskable.protobufs.AuthProto.internal_static_LoginExchangeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taskable.protobufs.AuthProto.LoginExchangeResponse.class, com.taskable.protobufs.AuthProto.LoginExchangeResponse.Builder.class);
      }

      // Construct using com.taskable.protobufs.AuthProto.LoginExchangeResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        csrfToken_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taskable.protobufs.AuthProto.internal_static_LoginExchangeResponse_descriptor;
      }

      @java.lang.Override
      public com.taskable.protobufs.AuthProto.LoginExchangeResponse getDefaultInstanceForType() {
        return com.taskable.protobufs.AuthProto.LoginExchangeResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.taskable.protobufs.AuthProto.LoginExchangeResponse build() {
        com.taskable.protobufs.AuthProto.LoginExchangeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taskable.protobufs.AuthProto.LoginExchangeResponse buildPartial() {
        com.taskable.protobufs.AuthProto.LoginExchangeResponse result = new com.taskable.protobufs.AuthProto.LoginExchangeResponse(this);
        result.csrfToken_ = csrfToken_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taskable.protobufs.AuthProto.LoginExchangeResponse) {
          return mergeFrom((com.taskable.protobufs.AuthProto.LoginExchangeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taskable.protobufs.AuthProto.LoginExchangeResponse other) {
        if (other == com.taskable.protobufs.AuthProto.LoginExchangeResponse.getDefaultInstance()) return this;
        if (!other.getCsrfToken().isEmpty()) {
          csrfToken_ = other.csrfToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                csrfToken_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object csrfToken_ = "";
      /**
       * <code>string csrf_token = 1;</code>
       * @return The csrfToken.
       */
      public java.lang.String getCsrfToken() {
        java.lang.Object ref = csrfToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          csrfToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string csrf_token = 1;</code>
       * @return The bytes for csrfToken.
       */
      public com.google.protobuf.ByteString
          getCsrfTokenBytes() {
        java.lang.Object ref = csrfToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          csrfToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string csrf_token = 1;</code>
       * @param value The csrfToken to set.
       * @return This builder for chaining.
       */
      public Builder setCsrfToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        csrfToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string csrf_token = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCsrfToken() {
        
        csrfToken_ = getDefaultInstance().getCsrfToken();
        onChanged();
        return this;
      }
      /**
       * <code>string csrf_token = 1;</code>
       * @param value The bytes for csrfToken to set.
       * @return This builder for chaining.
       */
      public Builder setCsrfTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        csrfToken_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginExchangeResponse)
    }

    // @@protoc_insertion_point(class_scope:LoginExchangeResponse)
    private static final com.taskable.protobufs.AuthProto.LoginExchangeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taskable.protobufs.AuthProto.LoginExchangeResponse();
    }

    public static com.taskable.protobufs.AuthProto.LoginExchangeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginExchangeResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginExchangeResponse>() {
      @java.lang.Override
      public LoginExchangeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginExchangeResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginExchangeResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taskable.protobufs.AuthProto.LoginExchangeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetCsrfResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetCsrfResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string csrf_token = 1;</code>
     * @return The csrfToken.
     */
    java.lang.String getCsrfToken();
    /**
     * <code>string csrf_token = 1;</code>
     * @return The bytes for csrfToken.
     */
    com.google.protobuf.ByteString
        getCsrfTokenBytes();
  }
  /**
   * Protobuf type {@code GetCsrfResponse}
   */
  public static final class GetCsrfResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetCsrfResponse)
      GetCsrfResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetCsrfResponse.newBuilder() to construct.
    private GetCsrfResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetCsrfResponse() {
      csrfToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetCsrfResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taskable.protobufs.AuthProto.internal_static_GetCsrfResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taskable.protobufs.AuthProto.internal_static_GetCsrfResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taskable.protobufs.AuthProto.GetCsrfResponse.class, com.taskable.protobufs.AuthProto.GetCsrfResponse.Builder.class);
    }

    public static final int CSRF_TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object csrfToken_;
    /**
     * <code>string csrf_token = 1;</code>
     * @return The csrfToken.
     */
    @java.lang.Override
    public java.lang.String getCsrfToken() {
      java.lang.Object ref = csrfToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        csrfToken_ = s;
        return s;
      }
    }
    /**
     * <code>string csrf_token = 1;</code>
     * @return The bytes for csrfToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCsrfTokenBytes() {
      java.lang.Object ref = csrfToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        csrfToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(csrfToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, csrfToken_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(csrfToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, csrfToken_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taskable.protobufs.AuthProto.GetCsrfResponse)) {
        return super.equals(obj);
      }
      com.taskable.protobufs.AuthProto.GetCsrfResponse other = (com.taskable.protobufs.AuthProto.GetCsrfResponse) obj;

      if (!getCsrfToken()
          .equals(other.getCsrfToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CSRF_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getCsrfToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.AuthProto.GetCsrfResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taskable.protobufs.AuthProto.GetCsrfResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetCsrfResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetCsrfResponse)
        com.taskable.protobufs.AuthProto.GetCsrfResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taskable.protobufs.AuthProto.internal_static_GetCsrfResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taskable.protobufs.AuthProto.internal_static_GetCsrfResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taskable.protobufs.AuthProto.GetCsrfResponse.class, com.taskable.protobufs.AuthProto.GetCsrfResponse.Builder.class);
      }

      // Construct using com.taskable.protobufs.AuthProto.GetCsrfResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        csrfToken_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taskable.protobufs.AuthProto.internal_static_GetCsrfResponse_descriptor;
      }

      @java.lang.Override
      public com.taskable.protobufs.AuthProto.GetCsrfResponse getDefaultInstanceForType() {
        return com.taskable.protobufs.AuthProto.GetCsrfResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.taskable.protobufs.AuthProto.GetCsrfResponse build() {
        com.taskable.protobufs.AuthProto.GetCsrfResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taskable.protobufs.AuthProto.GetCsrfResponse buildPartial() {
        com.taskable.protobufs.AuthProto.GetCsrfResponse result = new com.taskable.protobufs.AuthProto.GetCsrfResponse(this);
        result.csrfToken_ = csrfToken_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taskable.protobufs.AuthProto.GetCsrfResponse) {
          return mergeFrom((com.taskable.protobufs.AuthProto.GetCsrfResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taskable.protobufs.AuthProto.GetCsrfResponse other) {
        if (other == com.taskable.protobufs.AuthProto.GetCsrfResponse.getDefaultInstance()) return this;
        if (!other.getCsrfToken().isEmpty()) {
          csrfToken_ = other.csrfToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                csrfToken_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object csrfToken_ = "";
      /**
       * <code>string csrf_token = 1;</code>
       * @return The csrfToken.
       */
      public java.lang.String getCsrfToken() {
        java.lang.Object ref = csrfToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          csrfToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string csrf_token = 1;</code>
       * @return The bytes for csrfToken.
       */
      public com.google.protobuf.ByteString
          getCsrfTokenBytes() {
        java.lang.Object ref = csrfToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          csrfToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string csrf_token = 1;</code>
       * @param value The csrfToken to set.
       * @return This builder for chaining.
       */
      public Builder setCsrfToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        csrfToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string csrf_token = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCsrfToken() {
        
        csrfToken_ = getDefaultInstance().getCsrfToken();
        onChanged();
        return this;
      }
      /**
       * <code>string csrf_token = 1;</code>
       * @param value The bytes for csrfToken to set.
       * @return This builder for chaining.
       */
      public Builder setCsrfTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        csrfToken_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetCsrfResponse)
    }

    // @@protoc_insertion_point(class_scope:GetCsrfResponse)
    private static final com.taskable.protobufs.AuthProto.GetCsrfResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taskable.protobufs.AuthProto.GetCsrfResponse();
    }

    public static com.taskable.protobufs.AuthProto.GetCsrfResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCsrfResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetCsrfResponse>() {
      @java.lang.Override
      public GetCsrfResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetCsrfResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetCsrfResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taskable.protobufs.AuthProto.GetCsrfResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginExchangeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginExchangeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginExchangeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginExchangeResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCsrfResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCsrfResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\"2\n\024LoginExchangeRequest\022\032\n\022" +
      "authorization_code\030\001 \001(\t\"+\n\025LoginExchang" +
      "eResponse\022\022\n\ncsrf_token\030\001 \001(\t\"%\n\017GetCsrf" +
      "Response\022\022\n\ncsrf_token\030\001 \001(\tB#\n\026com.task" +
      "able.protobufsB\tAuthProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LoginExchangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginExchangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginExchangeRequest_descriptor,
        new java.lang.String[] { "AuthorizationCode", });
    internal_static_LoginExchangeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginExchangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginExchangeResponse_descriptor,
        new java.lang.String[] { "CsrfToken", });
    internal_static_GetCsrfResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetCsrfResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCsrfResponse_descriptor,
        new java.lang.String[] { "CsrfToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
