// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.taskable.protobufs;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetProfileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetProfileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.User user = 1;</code>
     * @return Whether the user field is set.
     */
    boolean hasUser();
    /**
     * <code>.User user = 1;</code>
     * @return The user.
     */
    com.taskable.protobufs.PersistenceProto.User getUser();
    /**
     * <code>.User user = 1;</code>
     */
    com.taskable.protobufs.PersistenceProto.UserOrBuilder getUserOrBuilder();
  }
  /**
   * Protobuf type {@code GetProfileResponse}
   */
  public static final class GetProfileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetProfileResponse)
      GetProfileResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetProfileResponse.newBuilder() to construct.
    private GetProfileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetProfileResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetProfileResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taskable.protobufs.UserProto.internal_static_GetProfileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taskable.protobufs.UserProto.internal_static_GetProfileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taskable.protobufs.UserProto.GetProfileResponse.class, com.taskable.protobufs.UserProto.GetProfileResponse.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private com.taskable.protobufs.PersistenceProto.User user_;
    /**
     * <code>.User user = 1;</code>
     * @return Whether the user field is set.
     */
    @java.lang.Override
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.User user = 1;</code>
     * @return The user.
     */
    @java.lang.Override
    public com.taskable.protobufs.PersistenceProto.User getUser() {
      return user_ == null ? com.taskable.protobufs.PersistenceProto.User.getDefaultInstance() : user_;
    }
    /**
     * <code>.User user = 1;</code>
     */
    @java.lang.Override
    public com.taskable.protobufs.PersistenceProto.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taskable.protobufs.UserProto.GetProfileResponse)) {
        return super.equals(obj);
      }
      com.taskable.protobufs.UserProto.GetProfileResponse other = (com.taskable.protobufs.UserProto.GetProfileResponse) obj;

      if (hasUser() != other.hasUser()) return false;
      if (hasUser()) {
        if (!getUser()
            .equals(other.getUser())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taskable.protobufs.UserProto.GetProfileResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.GetProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taskable.protobufs.UserProto.GetProfileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetProfileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetProfileResponse)
        com.taskable.protobufs.UserProto.GetProfileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taskable.protobufs.UserProto.internal_static_GetProfileResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taskable.protobufs.UserProto.internal_static_GetProfileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taskable.protobufs.UserProto.GetProfileResponse.class, com.taskable.protobufs.UserProto.GetProfileResponse.Builder.class);
      }

      // Construct using com.taskable.protobufs.UserProto.GetProfileResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taskable.protobufs.UserProto.internal_static_GetProfileResponse_descriptor;
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.GetProfileResponse getDefaultInstanceForType() {
        return com.taskable.protobufs.UserProto.GetProfileResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.GetProfileResponse build() {
        com.taskable.protobufs.UserProto.GetProfileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.GetProfileResponse buildPartial() {
        com.taskable.protobufs.UserProto.GetProfileResponse result = new com.taskable.protobufs.UserProto.GetProfileResponse(this);
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taskable.protobufs.UserProto.GetProfileResponse) {
          return mergeFrom((com.taskable.protobufs.UserProto.GetProfileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taskable.protobufs.UserProto.GetProfileResponse other) {
        if (other == com.taskable.protobufs.UserProto.GetProfileResponse.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getUserFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private com.taskable.protobufs.PersistenceProto.User user_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.taskable.protobufs.PersistenceProto.User, com.taskable.protobufs.PersistenceProto.User.Builder, com.taskable.protobufs.PersistenceProto.UserOrBuilder> userBuilder_;
      /**
       * <code>.User user = 1;</code>
       * @return Whether the user field is set.
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.User user = 1;</code>
       * @return The user.
       */
      public com.taskable.protobufs.PersistenceProto.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? com.taskable.protobufs.PersistenceProto.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.User user = 1;</code>
       */
      public Builder setUser(com.taskable.protobufs.PersistenceProto.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.User user = 1;</code>
       */
      public Builder setUser(
          com.taskable.protobufs.PersistenceProto.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.User user = 1;</code>
       */
      public Builder mergeUser(com.taskable.protobufs.PersistenceProto.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              com.taskable.protobufs.PersistenceProto.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.User user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.User user = 1;</code>
       */
      public com.taskable.protobufs.PersistenceProto.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.User user = 1;</code>
       */
      public com.taskable.protobufs.PersistenceProto.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              com.taskable.protobufs.PersistenceProto.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.User user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.taskable.protobufs.PersistenceProto.User, com.taskable.protobufs.PersistenceProto.User.Builder, com.taskable.protobufs.PersistenceProto.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.taskable.protobufs.PersistenceProto.User, com.taskable.protobufs.PersistenceProto.User.Builder, com.taskable.protobufs.PersistenceProto.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetProfileResponse)
    }

    // @@protoc_insertion_point(class_scope:GetProfileResponse)
    private static final com.taskable.protobufs.UserProto.GetProfileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taskable.protobufs.UserProto.GetProfileResponse();
    }

    public static com.taskable.protobufs.UserProto.GetProfileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetProfileResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetProfileResponse>() {
      @java.lang.Override
      public GetProfileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetProfileResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetProfileResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taskable.protobufs.UserProto.GetProfileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateProfileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UpdateProfileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.UserSettings user_settings = 1;</code>
     * @return Whether the userSettings field is set.
     */
    boolean hasUserSettings();
    /**
     * <code>.UserSettings user_settings = 1;</code>
     * @return The userSettings.
     */
    com.taskable.protobufs.PersistenceProto.UserSettings getUserSettings();
    /**
     * <code>.UserSettings user_settings = 1;</code>
     */
    com.taskable.protobufs.PersistenceProto.UserSettingsOrBuilder getUserSettingsOrBuilder();
  }
  /**
   * Protobuf type {@code UpdateProfileRequest}
   */
  public static final class UpdateProfileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UpdateProfileRequest)
      UpdateProfileRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateProfileRequest.newBuilder() to construct.
    private UpdateProfileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateProfileRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UpdateProfileRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taskable.protobufs.UserProto.internal_static_UpdateProfileRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taskable.protobufs.UserProto.internal_static_UpdateProfileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taskable.protobufs.UserProto.UpdateProfileRequest.class, com.taskable.protobufs.UserProto.UpdateProfileRequest.Builder.class);
    }

    public static final int USER_SETTINGS_FIELD_NUMBER = 1;
    private com.taskable.protobufs.PersistenceProto.UserSettings userSettings_;
    /**
     * <code>.UserSettings user_settings = 1;</code>
     * @return Whether the userSettings field is set.
     */
    @java.lang.Override
    public boolean hasUserSettings() {
      return userSettings_ != null;
    }
    /**
     * <code>.UserSettings user_settings = 1;</code>
     * @return The userSettings.
     */
    @java.lang.Override
    public com.taskable.protobufs.PersistenceProto.UserSettings getUserSettings() {
      return userSettings_ == null ? com.taskable.protobufs.PersistenceProto.UserSettings.getDefaultInstance() : userSettings_;
    }
    /**
     * <code>.UserSettings user_settings = 1;</code>
     */
    @java.lang.Override
    public com.taskable.protobufs.PersistenceProto.UserSettingsOrBuilder getUserSettingsOrBuilder() {
      return getUserSettings();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userSettings_ != null) {
        output.writeMessage(1, getUserSettings());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userSettings_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUserSettings());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taskable.protobufs.UserProto.UpdateProfileRequest)) {
        return super.equals(obj);
      }
      com.taskable.protobufs.UserProto.UpdateProfileRequest other = (com.taskable.protobufs.UserProto.UpdateProfileRequest) obj;

      if (hasUserSettings() != other.hasUserSettings()) return false;
      if (hasUserSettings()) {
        if (!getUserSettings()
            .equals(other.getUserSettings())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserSettings()) {
        hash = (37 * hash) + USER_SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getUserSettings().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.UpdateProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taskable.protobufs.UserProto.UpdateProfileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UpdateProfileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UpdateProfileRequest)
        com.taskable.protobufs.UserProto.UpdateProfileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taskable.protobufs.UserProto.internal_static_UpdateProfileRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taskable.protobufs.UserProto.internal_static_UpdateProfileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taskable.protobufs.UserProto.UpdateProfileRequest.class, com.taskable.protobufs.UserProto.UpdateProfileRequest.Builder.class);
      }

      // Construct using com.taskable.protobufs.UserProto.UpdateProfileRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userSettingsBuilder_ == null) {
          userSettings_ = null;
        } else {
          userSettings_ = null;
          userSettingsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taskable.protobufs.UserProto.internal_static_UpdateProfileRequest_descriptor;
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.UpdateProfileRequest getDefaultInstanceForType() {
        return com.taskable.protobufs.UserProto.UpdateProfileRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.UpdateProfileRequest build() {
        com.taskable.protobufs.UserProto.UpdateProfileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.UpdateProfileRequest buildPartial() {
        com.taskable.protobufs.UserProto.UpdateProfileRequest result = new com.taskable.protobufs.UserProto.UpdateProfileRequest(this);
        if (userSettingsBuilder_ == null) {
          result.userSettings_ = userSettings_;
        } else {
          result.userSettings_ = userSettingsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taskable.protobufs.UserProto.UpdateProfileRequest) {
          return mergeFrom((com.taskable.protobufs.UserProto.UpdateProfileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taskable.protobufs.UserProto.UpdateProfileRequest other) {
        if (other == com.taskable.protobufs.UserProto.UpdateProfileRequest.getDefaultInstance()) return this;
        if (other.hasUserSettings()) {
          mergeUserSettings(other.getUserSettings());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getUserSettingsFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private com.taskable.protobufs.PersistenceProto.UserSettings userSettings_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.taskable.protobufs.PersistenceProto.UserSettings, com.taskable.protobufs.PersistenceProto.UserSettings.Builder, com.taskable.protobufs.PersistenceProto.UserSettingsOrBuilder> userSettingsBuilder_;
      /**
       * <code>.UserSettings user_settings = 1;</code>
       * @return Whether the userSettings field is set.
       */
      public boolean hasUserSettings() {
        return userSettingsBuilder_ != null || userSettings_ != null;
      }
      /**
       * <code>.UserSettings user_settings = 1;</code>
       * @return The userSettings.
       */
      public com.taskable.protobufs.PersistenceProto.UserSettings getUserSettings() {
        if (userSettingsBuilder_ == null) {
          return userSettings_ == null ? com.taskable.protobufs.PersistenceProto.UserSettings.getDefaultInstance() : userSettings_;
        } else {
          return userSettingsBuilder_.getMessage();
        }
      }
      /**
       * <code>.UserSettings user_settings = 1;</code>
       */
      public Builder setUserSettings(com.taskable.protobufs.PersistenceProto.UserSettings value) {
        if (userSettingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userSettings_ = value;
          onChanged();
        } else {
          userSettingsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.UserSettings user_settings = 1;</code>
       */
      public Builder setUserSettings(
          com.taskable.protobufs.PersistenceProto.UserSettings.Builder builderForValue) {
        if (userSettingsBuilder_ == null) {
          userSettings_ = builderForValue.build();
          onChanged();
        } else {
          userSettingsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.UserSettings user_settings = 1;</code>
       */
      public Builder mergeUserSettings(com.taskable.protobufs.PersistenceProto.UserSettings value) {
        if (userSettingsBuilder_ == null) {
          if (userSettings_ != null) {
            userSettings_ =
              com.taskable.protobufs.PersistenceProto.UserSettings.newBuilder(userSettings_).mergeFrom(value).buildPartial();
          } else {
            userSettings_ = value;
          }
          onChanged();
        } else {
          userSettingsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.UserSettings user_settings = 1;</code>
       */
      public Builder clearUserSettings() {
        if (userSettingsBuilder_ == null) {
          userSettings_ = null;
          onChanged();
        } else {
          userSettings_ = null;
          userSettingsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.UserSettings user_settings = 1;</code>
       */
      public com.taskable.protobufs.PersistenceProto.UserSettings.Builder getUserSettingsBuilder() {
        
        onChanged();
        return getUserSettingsFieldBuilder().getBuilder();
      }
      /**
       * <code>.UserSettings user_settings = 1;</code>
       */
      public com.taskable.protobufs.PersistenceProto.UserSettingsOrBuilder getUserSettingsOrBuilder() {
        if (userSettingsBuilder_ != null) {
          return userSettingsBuilder_.getMessageOrBuilder();
        } else {
          return userSettings_ == null ?
              com.taskable.protobufs.PersistenceProto.UserSettings.getDefaultInstance() : userSettings_;
        }
      }
      /**
       * <code>.UserSettings user_settings = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.taskable.protobufs.PersistenceProto.UserSettings, com.taskable.protobufs.PersistenceProto.UserSettings.Builder, com.taskable.protobufs.PersistenceProto.UserSettingsOrBuilder> 
          getUserSettingsFieldBuilder() {
        if (userSettingsBuilder_ == null) {
          userSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.taskable.protobufs.PersistenceProto.UserSettings, com.taskable.protobufs.PersistenceProto.UserSettings.Builder, com.taskable.protobufs.PersistenceProto.UserSettingsOrBuilder>(
                  getUserSettings(),
                  getParentForChildren(),
                  isClean());
          userSettings_ = null;
        }
        return userSettingsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UpdateProfileRequest)
    }

    // @@protoc_insertion_point(class_scope:UpdateProfileRequest)
    private static final com.taskable.protobufs.UserProto.UpdateProfileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taskable.protobufs.UserProto.UpdateProfileRequest();
    }

    public static com.taskable.protobufs.UserProto.UpdateProfileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateProfileRequest>
        PARSER = new com.google.protobuf.AbstractParser<UpdateProfileRequest>() {
      @java.lang.Override
      public UpdateProfileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UpdateProfileRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateProfileRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taskable.protobufs.UserProto.UpdateProfileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchUserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SearchUserRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string emails = 1;</code>
     * @return A list containing the emails.
     */
    java.util.List<java.lang.String>
        getEmailsList();
    /**
     * <code>repeated string emails = 1;</code>
     * @return The count of emails.
     */
    int getEmailsCount();
    /**
     * <code>repeated string emails = 1;</code>
     * @param index The index of the element to return.
     * @return The emails at the given index.
     */
    java.lang.String getEmails(int index);
    /**
     * <code>repeated string emails = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the emails at the given index.
     */
    com.google.protobuf.ByteString
        getEmailsBytes(int index);
  }
  /**
   * Protobuf type {@code SearchUserRequest}
   */
  public static final class SearchUserRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SearchUserRequest)
      SearchUserRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchUserRequest.newBuilder() to construct.
    private SearchUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchUserRequest() {
      emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchUserRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taskable.protobufs.UserProto.internal_static_SearchUserRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taskable.protobufs.UserProto.internal_static_SearchUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taskable.protobufs.UserProto.SearchUserRequest.class, com.taskable.protobufs.UserProto.SearchUserRequest.Builder.class);
    }

    public static final int EMAILS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList emails_;
    /**
     * <code>repeated string emails = 1;</code>
     * @return A list containing the emails.
     */
    public com.google.protobuf.ProtocolStringList
        getEmailsList() {
      return emails_;
    }
    /**
     * <code>repeated string emails = 1;</code>
     * @return The count of emails.
     */
    public int getEmailsCount() {
      return emails_.size();
    }
    /**
     * <code>repeated string emails = 1;</code>
     * @param index The index of the element to return.
     * @return The emails at the given index.
     */
    public java.lang.String getEmails(int index) {
      return emails_.get(index);
    }
    /**
     * <code>repeated string emails = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the emails at the given index.
     */
    public com.google.protobuf.ByteString
        getEmailsBytes(int index) {
      return emails_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < emails_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, emails_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < emails_.size(); i++) {
          dataSize += computeStringSizeNoTag(emails_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getEmailsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taskable.protobufs.UserProto.SearchUserRequest)) {
        return super.equals(obj);
      }
      com.taskable.protobufs.UserProto.SearchUserRequest other = (com.taskable.protobufs.UserProto.SearchUserRequest) obj;

      if (!getEmailsList()
          .equals(other.getEmailsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEmailsCount() > 0) {
        hash = (37 * hash) + EMAILS_FIELD_NUMBER;
        hash = (53 * hash) + getEmailsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taskable.protobufs.UserProto.SearchUserRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.SearchUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taskable.protobufs.UserProto.SearchUserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SearchUserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SearchUserRequest)
        com.taskable.protobufs.UserProto.SearchUserRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taskable.protobufs.UserProto.internal_static_SearchUserRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taskable.protobufs.UserProto.internal_static_SearchUserRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taskable.protobufs.UserProto.SearchUserRequest.class, com.taskable.protobufs.UserProto.SearchUserRequest.Builder.class);
      }

      // Construct using com.taskable.protobufs.UserProto.SearchUserRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taskable.protobufs.UserProto.internal_static_SearchUserRequest_descriptor;
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.SearchUserRequest getDefaultInstanceForType() {
        return com.taskable.protobufs.UserProto.SearchUserRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.SearchUserRequest build() {
        com.taskable.protobufs.UserProto.SearchUserRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.SearchUserRequest buildPartial() {
        com.taskable.protobufs.UserProto.SearchUserRequest result = new com.taskable.protobufs.UserProto.SearchUserRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          emails_ = emails_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.emails_ = emails_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taskable.protobufs.UserProto.SearchUserRequest) {
          return mergeFrom((com.taskable.protobufs.UserProto.SearchUserRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taskable.protobufs.UserProto.SearchUserRequest other) {
        if (other == com.taskable.protobufs.UserProto.SearchUserRequest.getDefaultInstance()) return this;
        if (!other.emails_.isEmpty()) {
          if (emails_.isEmpty()) {
            emails_ = other.emails_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmailsIsMutable();
            emails_.addAll(other.emails_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureEmailsIsMutable();
                emails_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEmailsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          emails_ = new com.google.protobuf.LazyStringArrayList(emails_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string emails = 1;</code>
       * @return A list containing the emails.
       */
      public com.google.protobuf.ProtocolStringList
          getEmailsList() {
        return emails_.getUnmodifiableView();
      }
      /**
       * <code>repeated string emails = 1;</code>
       * @return The count of emails.
       */
      public int getEmailsCount() {
        return emails_.size();
      }
      /**
       * <code>repeated string emails = 1;</code>
       * @param index The index of the element to return.
       * @return The emails at the given index.
       */
      public java.lang.String getEmails(int index) {
        return emails_.get(index);
      }
      /**
       * <code>repeated string emails = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the emails at the given index.
       */
      public com.google.protobuf.ByteString
          getEmailsBytes(int index) {
        return emails_.getByteString(index);
      }
      /**
       * <code>repeated string emails = 1;</code>
       * @param index The index to set the value at.
       * @param value The emails to set.
       * @return This builder for chaining.
       */
      public Builder setEmails(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailsIsMutable();
        emails_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string emails = 1;</code>
       * @param value The emails to add.
       * @return This builder for chaining.
       */
      public Builder addEmails(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailsIsMutable();
        emails_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string emails = 1;</code>
       * @param values The emails to add.
       * @return This builder for chaining.
       */
      public Builder addAllEmails(
          java.lang.Iterable<java.lang.String> values) {
        ensureEmailsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, emails_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string emails = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmails() {
        emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string emails = 1;</code>
       * @param value The bytes of the emails to add.
       * @return This builder for chaining.
       */
      public Builder addEmailsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureEmailsIsMutable();
        emails_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SearchUserRequest)
    }

    // @@protoc_insertion_point(class_scope:SearchUserRequest)
    private static final com.taskable.protobufs.UserProto.SearchUserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taskable.protobufs.UserProto.SearchUserRequest();
    }

    public static com.taskable.protobufs.UserProto.SearchUserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchUserRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchUserRequest>() {
      @java.lang.Override
      public SearchUserRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SearchUserRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchUserRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taskable.protobufs.UserProto.SearchUserRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchUserResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SearchUserResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string invalid_emails = 1;</code>
     * @return A list containing the invalidEmails.
     */
    java.util.List<java.lang.String>
        getInvalidEmailsList();
    /**
     * <code>repeated string invalid_emails = 1;</code>
     * @return The count of invalidEmails.
     */
    int getInvalidEmailsCount();
    /**
     * <code>repeated string invalid_emails = 1;</code>
     * @param index The index of the element to return.
     * @return The invalidEmails at the given index.
     */
    java.lang.String getInvalidEmails(int index);
    /**
     * <code>repeated string invalid_emails = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the invalidEmails at the given index.
     */
    com.google.protobuf.ByteString
        getInvalidEmailsBytes(int index);
  }
  /**
   * Protobuf type {@code SearchUserResponse}
   */
  public static final class SearchUserResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SearchUserResponse)
      SearchUserResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchUserResponse.newBuilder() to construct.
    private SearchUserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchUserResponse() {
      invalidEmails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchUserResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taskable.protobufs.UserProto.internal_static_SearchUserResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taskable.protobufs.UserProto.internal_static_SearchUserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taskable.protobufs.UserProto.SearchUserResponse.class, com.taskable.protobufs.UserProto.SearchUserResponse.Builder.class);
    }

    public static final int INVALID_EMAILS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList invalidEmails_;
    /**
     * <code>repeated string invalid_emails = 1;</code>
     * @return A list containing the invalidEmails.
     */
    public com.google.protobuf.ProtocolStringList
        getInvalidEmailsList() {
      return invalidEmails_;
    }
    /**
     * <code>repeated string invalid_emails = 1;</code>
     * @return The count of invalidEmails.
     */
    public int getInvalidEmailsCount() {
      return invalidEmails_.size();
    }
    /**
     * <code>repeated string invalid_emails = 1;</code>
     * @param index The index of the element to return.
     * @return The invalidEmails at the given index.
     */
    public java.lang.String getInvalidEmails(int index) {
      return invalidEmails_.get(index);
    }
    /**
     * <code>repeated string invalid_emails = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the invalidEmails at the given index.
     */
    public com.google.protobuf.ByteString
        getInvalidEmailsBytes(int index) {
      return invalidEmails_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < invalidEmails_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, invalidEmails_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < invalidEmails_.size(); i++) {
          dataSize += computeStringSizeNoTag(invalidEmails_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInvalidEmailsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taskable.protobufs.UserProto.SearchUserResponse)) {
        return super.equals(obj);
      }
      com.taskable.protobufs.UserProto.SearchUserResponse other = (com.taskable.protobufs.UserProto.SearchUserResponse) obj;

      if (!getInvalidEmailsList()
          .equals(other.getInvalidEmailsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getInvalidEmailsCount() > 0) {
        hash = (37 * hash) + INVALID_EMAILS_FIELD_NUMBER;
        hash = (53 * hash) + getInvalidEmailsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taskable.protobufs.UserProto.SearchUserResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taskable.protobufs.UserProto.SearchUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taskable.protobufs.UserProto.SearchUserResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SearchUserResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SearchUserResponse)
        com.taskable.protobufs.UserProto.SearchUserResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taskable.protobufs.UserProto.internal_static_SearchUserResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taskable.protobufs.UserProto.internal_static_SearchUserResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taskable.protobufs.UserProto.SearchUserResponse.class, com.taskable.protobufs.UserProto.SearchUserResponse.Builder.class);
      }

      // Construct using com.taskable.protobufs.UserProto.SearchUserResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        invalidEmails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taskable.protobufs.UserProto.internal_static_SearchUserResponse_descriptor;
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.SearchUserResponse getDefaultInstanceForType() {
        return com.taskable.protobufs.UserProto.SearchUserResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.SearchUserResponse build() {
        com.taskable.protobufs.UserProto.SearchUserResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taskable.protobufs.UserProto.SearchUserResponse buildPartial() {
        com.taskable.protobufs.UserProto.SearchUserResponse result = new com.taskable.protobufs.UserProto.SearchUserResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          invalidEmails_ = invalidEmails_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.invalidEmails_ = invalidEmails_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taskable.protobufs.UserProto.SearchUserResponse) {
          return mergeFrom((com.taskable.protobufs.UserProto.SearchUserResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taskable.protobufs.UserProto.SearchUserResponse other) {
        if (other == com.taskable.protobufs.UserProto.SearchUserResponse.getDefaultInstance()) return this;
        if (!other.invalidEmails_.isEmpty()) {
          if (invalidEmails_.isEmpty()) {
            invalidEmails_ = other.invalidEmails_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInvalidEmailsIsMutable();
            invalidEmails_.addAll(other.invalidEmails_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureInvalidEmailsIsMutable();
                invalidEmails_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList invalidEmails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInvalidEmailsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          invalidEmails_ = new com.google.protobuf.LazyStringArrayList(invalidEmails_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string invalid_emails = 1;</code>
       * @return A list containing the invalidEmails.
       */
      public com.google.protobuf.ProtocolStringList
          getInvalidEmailsList() {
        return invalidEmails_.getUnmodifiableView();
      }
      /**
       * <code>repeated string invalid_emails = 1;</code>
       * @return The count of invalidEmails.
       */
      public int getInvalidEmailsCount() {
        return invalidEmails_.size();
      }
      /**
       * <code>repeated string invalid_emails = 1;</code>
       * @param index The index of the element to return.
       * @return The invalidEmails at the given index.
       */
      public java.lang.String getInvalidEmails(int index) {
        return invalidEmails_.get(index);
      }
      /**
       * <code>repeated string invalid_emails = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the invalidEmails at the given index.
       */
      public com.google.protobuf.ByteString
          getInvalidEmailsBytes(int index) {
        return invalidEmails_.getByteString(index);
      }
      /**
       * <code>repeated string invalid_emails = 1;</code>
       * @param index The index to set the value at.
       * @param value The invalidEmails to set.
       * @return This builder for chaining.
       */
      public Builder setInvalidEmails(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInvalidEmailsIsMutable();
        invalidEmails_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string invalid_emails = 1;</code>
       * @param value The invalidEmails to add.
       * @return This builder for chaining.
       */
      public Builder addInvalidEmails(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInvalidEmailsIsMutable();
        invalidEmails_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string invalid_emails = 1;</code>
       * @param values The invalidEmails to add.
       * @return This builder for chaining.
       */
      public Builder addAllInvalidEmails(
          java.lang.Iterable<java.lang.String> values) {
        ensureInvalidEmailsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invalidEmails_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string invalid_emails = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInvalidEmails() {
        invalidEmails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string invalid_emails = 1;</code>
       * @param value The bytes of the invalidEmails to add.
       * @return This builder for chaining.
       */
      public Builder addInvalidEmailsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInvalidEmailsIsMutable();
        invalidEmails_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SearchUserResponse)
    }

    // @@protoc_insertion_point(class_scope:SearchUserResponse)
    private static final com.taskable.protobufs.UserProto.SearchUserResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taskable.protobufs.UserProto.SearchUserResponse();
    }

    public static com.taskable.protobufs.UserProto.SearchUserResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchUserResponse>
        PARSER = new com.google.protobuf.AbstractParser<SearchUserResponse>() {
      @java.lang.Override
      public SearchUserResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SearchUserResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchUserResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taskable.protobufs.UserProto.SearchUserResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetProfileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetProfileResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateProfileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateProfileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchUserRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchUserRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchUserResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\032\021persistence.proto\")\n\022GetPr" +
      "ofileResponse\022\023\n\004user\030\001 \001(\0132\005.User\"<\n\024Up" +
      "dateProfileRequest\022$\n\ruser_settings\030\001 \001(" +
      "\0132\r.UserSettings\"#\n\021SearchUserRequest\022\016\n" +
      "\006emails\030\001 \003(\t\",\n\022SearchUserResponse\022\026\n\016i" +
      "nvalid_emails\030\001 \003(\tB#\n\026com.taskable.prot" +
      "obufsB\tUserProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.taskable.protobufs.PersistenceProto.getDescriptor(),
        });
    internal_static_GetProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetProfileResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_UpdateProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UpdateProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateProfileRequest_descriptor,
        new java.lang.String[] { "UserSettings", });
    internal_static_SearchUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SearchUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchUserRequest_descriptor,
        new java.lang.String[] { "Emails", });
    internal_static_SearchUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SearchUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchUserResponse_descriptor,
        new java.lang.String[] { "InvalidEmails", });
    com.taskable.protobufs.PersistenceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
