/*
 * This file is generated by jOOQ.
 */
package com.taskable.jooq;


import com.taskable.jooq.tables.ClassroomUser;
import com.taskable.jooq.tables.Project;
import com.taskable.jooq.tables.Template;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in testdb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CLASSROOM_USER_CLASSROOM_ID = Internal.createIndex(DSL.name("classroom_id"), ClassroomUser.CLASSROOM_USER, new OrderField[] { ClassroomUser.CLASSROOM_USER.CLASSROOM_ID }, false);
    public static final Index TEMPLATE_CLASSROOM_ID = Internal.createIndex(DSL.name("classroom_id"), Template.TEMPLATE, new OrderField[] { Template.TEMPLATE.CLASSROOM_ID }, false);
    public static final Index PROJECT_TEMPLATE_ID = Internal.createIndex(DSL.name("template_id"), Project.PROJECT, new OrderField[] { Project.PROJECT.TEMPLATE_ID }, false);
}
