/*
 * This file is generated by jOOQ.
 */
package com.taskable.jooq;


import com.taskable.jooq.tables.Classroom;
import com.taskable.jooq.tables.ClassroomUser;
import com.taskable.jooq.tables.Project;
import com.taskable.jooq.tables.Template;
import com.taskable.jooq.tables.User;


/**
 * Convenience access to all tables in testdb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>testdb.classroom</code>.
     */
    public static final Classroom CLASSROOM = Classroom.CLASSROOM;

    /**
     * The table <code>testdb.classroom_user</code>.
     */
    public static final ClassroomUser CLASSROOM_USER = ClassroomUser.CLASSROOM_USER;

    /**
     * The table <code>testdb.project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>testdb.template</code>.
     */
    public static final Template TEMPLATE = Template.TEMPLATE;

    /**
     * The table <code>testdb.user</code>.
     */
    public static final User USER = User.USER;
}
