/*
 * This file is generated by jOOQ.
 */
package com.taskable.jooq;


import com.taskable.jooq.tables.Classroom;
import com.taskable.jooq.tables.ClassroomUser;
import com.taskable.jooq.tables.Project;
import com.taskable.jooq.tables.ProjectUser;
import com.taskable.jooq.tables.Subtask;
import com.taskable.jooq.tables.SubtaskAssignee;
import com.taskable.jooq.tables.SubtaskComment;
import com.taskable.jooq.tables.Task;
import com.taskable.jooq.tables.Template;
import com.taskable.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Testdb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>testdb</code>
     */
    public static final Testdb TESTDB = new Testdb();

    /**
     * The table <code>testdb.classroom</code>.
     */
    public final Classroom CLASSROOM = Classroom.CLASSROOM;

    /**
     * The table <code>testdb.classroom_user</code>.
     */
    public final ClassroomUser CLASSROOM_USER = ClassroomUser.CLASSROOM_USER;

    /**
     * The table <code>testdb.project</code>.
     */
    public final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>testdb.project_user</code>.
     */
    public final ProjectUser PROJECT_USER = ProjectUser.PROJECT_USER;

    /**
     * The table <code>testdb.subtask</code>.
     */
    public final Subtask SUBTASK = Subtask.SUBTASK;

    /**
     * The table <code>testdb.subtask_assignee</code>.
     */
    public final SubtaskAssignee SUBTASK_ASSIGNEE = SubtaskAssignee.SUBTASK_ASSIGNEE;

    /**
     * The table <code>testdb.subtask_comment</code>.
     */
    public final SubtaskComment SUBTASK_COMMENT = SubtaskComment.SUBTASK_COMMENT;

    /**
     * The table <code>testdb.task</code>.
     */
    public final Task TASK = Task.TASK;

    /**
     * The table <code>testdb.template</code>.
     */
    public final Template TEMPLATE = Template.TEMPLATE;

    /**
     * The table <code>testdb.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Testdb() {
        super("testdb", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Classroom.CLASSROOM,
            ClassroomUser.CLASSROOM_USER,
            Project.PROJECT,
            ProjectUser.PROJECT_USER,
            Subtask.SUBTASK,
            SubtaskAssignee.SUBTASK_ASSIGNEE,
            SubtaskComment.SUBTASK_COMMENT,
            Task.TASK,
            Template.TEMPLATE,
            User.USER
        );
    }
}
