/*
 * This file is generated by jOOQ.
 */
package com.taskable.jooq.tables;


import com.taskable.jooq.Indexes;
import com.taskable.jooq.Keys;
import com.taskable.jooq.Testdb;
import com.taskable.jooq.tables.Classroom.ClassroomPath;
import com.taskable.jooq.tables.User.UserPath;
import com.taskable.jooq.tables.records.ClassroomUserRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassroomUser extends TableImpl<ClassroomUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>testdb.classroom_user</code>
     */
    public static final ClassroomUser CLASSROOM_USER = new ClassroomUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClassroomUserRecord> getRecordType() {
        return ClassroomUserRecord.class;
    }

    /**
     * The column <code>testdb.classroom_user.user_id</code>.
     */
    public final TableField<ClassroomUserRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>testdb.classroom_user.classroom_id</code>.
     */
    public final TableField<ClassroomUserRecord, Integer> CLASSROOM_ID = createField(DSL.name("classroom_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>testdb.classroom_user.role</code>.
     */
    public final TableField<ClassroomUserRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private ClassroomUser(Name alias, Table<ClassroomUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClassroomUser(Name alias, Table<ClassroomUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>testdb.classroom_user</code> table reference
     */
    public ClassroomUser(String alias) {
        this(DSL.name(alias), CLASSROOM_USER);
    }

    /**
     * Create an aliased <code>testdb.classroom_user</code> table reference
     */
    public ClassroomUser(Name alias) {
        this(alias, CLASSROOM_USER);
    }

    /**
     * Create a <code>testdb.classroom_user</code> table reference
     */
    public ClassroomUser() {
        this(DSL.name("classroom_user"), null);
    }

    public <O extends Record> ClassroomUser(Table<O> path, ForeignKey<O, ClassroomUserRecord> childPath, InverseForeignKey<O, ClassroomUserRecord> parentPath) {
        super(path, childPath, parentPath, CLASSROOM_USER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClassroomUserPath extends ClassroomUser implements Path<ClassroomUserRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClassroomUserPath(Table<O> path, ForeignKey<O, ClassroomUserRecord> childPath, InverseForeignKey<O, ClassroomUserRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClassroomUserPath(Name alias, Table<ClassroomUserRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClassroomUserPath as(String alias) {
            return new ClassroomUserPath(DSL.name(alias), this);
        }

        @Override
        public ClassroomUserPath as(Name alias) {
            return new ClassroomUserPath(alias, this);
        }

        @Override
        public ClassroomUserPath as(Table<?> alias) {
            return new ClassroomUserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Testdb.TESTDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CLASSROOM_USER_CLASSROOM_ID);
    }

    @Override
    public UniqueKey<ClassroomUserRecord> getPrimaryKey() {
        return Keys.KEY_CLASSROOM_USER_PRIMARY;
    }

    @Override
    public List<ForeignKey<ClassroomUserRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLASSROOM_USER_IBFK_1, Keys.CLASSROOM_USER_IBFK_2);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>testdb.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.CLASSROOM_USER_IBFK_1, null);

        return _user;
    }

    private transient ClassroomPath _classroom;

    /**
     * Get the implicit join path to the <code>testdb.classroom</code> table.
     */
    public ClassroomPath classroom() {
        if (_classroom == null)
            _classroom = new ClassroomPath(this, Keys.CLASSROOM_USER_IBFK_2, null);

        return _classroom;
    }

    @Override
    public ClassroomUser as(String alias) {
        return new ClassroomUser(DSL.name(alias), this);
    }

    @Override
    public ClassroomUser as(Name alias) {
        return new ClassroomUser(alias, this);
    }

    @Override
    public ClassroomUser as(Table<?> alias) {
        return new ClassroomUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassroomUser rename(String name) {
        return new ClassroomUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassroomUser rename(Name name) {
        return new ClassroomUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassroomUser rename(Table<?> name) {
        return new ClassroomUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassroomUser where(Condition condition) {
        return new ClassroomUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassroomUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassroomUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassroomUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassroomUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassroomUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassroomUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassroomUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassroomUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassroomUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
