/*
 * This file is generated by jOOQ.
 */
package com.taskable.backend.jooq;


import com.taskable.backend.jooq.tables.Users;


/**
 * Convenience access to all tables in testdb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>testdb.Users</code>.
     */
    public static final Users USERS = Users.USERS;
}
